version: "3"

services:
  flask:
    build: .
    container_name: flask
    ports:
      - 5000:5000
    links:
      - mongo

  mongo:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=portfolioDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: